# <img src="uni-logo.png" alt="Logo UNI" width=100 hight=200 align="right">


<br><br><br>
<h1><font color="#7F000E" size=5>POO con Python</font></h1>



<h1><font color="#7F000E" size=6>Módulo 2: Numpy III</font></h1>

<br>
<div style="text-align: right">
<font color="#7F000E" size=3>Jose Lizarraga Trebejo</font><br>
<font color="#7F000E" size=3>Ing. Telecom</font><br>
<font color="#7F000E" size=3>Ciencias de la Computación</font><br>
</div>

---

<a id="indice"></a>
<h2><font color="#004D7F" size=5>Índice</font></h2>


* [10. Manipulación de arrays](#section10)
   * [Cambio de dimensiones](#section101)
   * [Redimensionamiento (cambio del número de elementos)](#section102)
   * [_Padding_](#section103)
   * [Unión de arrays](#section104)   
   * [Replicación de arrays](#section105)      
   * [División de arrays](#section106)       
   * [Adición y borrado de elemenetos](#section107)        

* [11. Arrays con tipos de datos heterogéneos y estructurados](#section11)
* [13. Almacenamiento de datos](#section12)
* [13. _Broadcasting_](#section13)

---

<a id="section10"></a> 
<h2><font color="#004D7F" size=5> 10. Manipulación de arrays</font></h2>

--- 

<a id="section101"></a> 
<h2><font color="#004D7F" size=4> Cambio de dimensiones </font></h2>

Mediante `reshape()` se crea una *vista* del vector con las dimensiones pasadas como parámetros. Es decir, ambos comparten datos, por lo que si se cambia un elemento en el segundo array,  el cambio se aprecia en el primero.

In [1]:
import numpy as np
c = np.array([[[1], [2]], [[3], [4]]])
print(c)
print(c.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [1]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
b[0,0]=20                   
print(a)

[20  2  3  4  5  6]


Los métodos `flatten()` y `ravel()` redimensionan el array a una dimensión. La diferencia entre ellos es que `flatten()` devuelve una copia del array, y `ravel()` devuelve una vista, por lo que un cambio en el vector devuelto afecta al array original.

In [2]:
m1 = np.array([[1,2,3],[4,5,6]])
v1 = m1.flatten()
print(v1)                  # Imprime el vector
v1[0] = 10      
print(m1)                  # La matriz es similar 

print()
v2 = m1.ravel()
v2[0] = 10
print(m1)                  # Ahora la matriz m1 sí que cambia

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]

[[10  2  3]
 [ 4  5  6]]


Existen varias funciones para cambiar el número de dimensiones de un array. La función `expand_dims()` permite añadir una dimensión al array en el eje especificado, _devolviendo una vista_. 

In [3]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print()

b = np.expand_dims(a, axis=0)
print(b)
print(b.shape)
print()

c = np.expand_dims(a, axis=1)
print(c)
print(c.shape)

[1 2 3 4 5 6]
(6,)

[[1 2 3 4 5 6]]
(1, 6)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


La función `squeeze()` permite eliminar las dimensiones en las que solamente existe un elemento. 

In [6]:
print(b.shape)
print(b)

s = np.squeeze(b, axis=0)
print(s.shape)
print(s)

# print(np.squeeze(b, axis=1))           # Esta llamada daría error porque el tamaño de esa dimensión no es uno.

(1, 6)
[[1 2 3 4 5 6]]
(6,)
[1 2 3 4 5 6]


---

<a id="section102"></a> 
<h2><font color="#004D7F" size=4> Redimensionamiento (cambio del número de elementos) </font></h2>

El método `resize()` permite cambiar el tamaño del array. Cambia la forma del array, y añade los elementos de uno en uno. Si el nuevo tamaño es superior, se copian (repiten) elementos. Si es menor, se descartan.

In [7]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.flatten())
print()

ar = np.resize(a,(4,3))
print(ar)
print()

ar2 = np.resize(a,(4,4))
print(ar2)
print()

ar3 = np.resize(a,(2,2))
print(ar3)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]
 [1 2 3 4]]

[[1 2]
 [3 4]]


---

<a id="section103"></a> 
<h2><font color="#004D7F" size=4> <i>Padding</i> </font></h2>

Consiste en ampliar el tamaño del array y rellenar las nuevas posiciones con valores determinados. La función `pad()` implementa varias opciones relativas al modo en que se calculan los nuevos valores (cuando no son constantes) o la forma del nuevo array ([documentación de pad](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.pad.html#numpy.pad)).

Por ejemplo, el siguiente código crea un vector de 10 elementos. Posteriormente añade 2 elementos al principio y 4 al final. A los dos primeros les asigna el valor 0, y a los cuatro últimos 10. La segunda llamada a `pad()` rellena las nuevas posiciones con el valor del extremo correspondiente.

In [8]:
v = np.array(np.arange(0,10))
print(v)

print(np.pad(v, (2,4), 'constant', constant_values=(0, 10)))
print(np.pad(v, (2, 3), 'edge'))

[0 1 2 3 4 5 6 7 8 9]
[ 0  0  0  1  2  3  4  5  6  7  8  9 10 10 10 10]
[0 0 0 1 2 3 4 5 6 7 8 9 9 9 9]


El siguiente código añade dos filas arriba y cuatro abajo; y una columna a la izquierda y 5 a la derecha. Cada una la rellena con el valor correspondiente. Como puede verse se sigue un orden al rellenarlas. La segunda llamada rellena cada posición con el valor del extremo correspondiente.

In [9]:
m = np.array([[1,2,3],[4,5,6]])
print(m)

print(np.pad(m, ((2,4),(1,5)), 'constant', constant_values=((100, 200),(10,20))),"\n")

print(np.pad(m, ((2,4),(1,5)), 'edge'),"\n")

[[1 2 3]
 [4 5 6]]
[[ 10 100 100 100  20  20  20  20  20]
 [ 10 100 100 100  20  20  20  20  20]
 [ 10   1   2   3  20  20  20  20  20]
 [ 10   4   5   6  20  20  20  20  20]
 [ 10 200 200 200  20  20  20  20  20]
 [ 10 200 200 200  20  20  20  20  20]
 [ 10 200 200 200  20  20  20  20  20]
 [ 10 200 200 200  20  20  20  20  20]] 

[[1 1 2 3 3 3 3 3 3]
 [1 1 2 3 3 3 3 3 3]
 [1 1 2 3 3 3 3 3 3]
 [4 4 5 6 6 6 6 6 6]
 [4 4 5 6 6 6 6 6 6]
 [4 4 5 6 6 6 6 6 6]
 [4 4 5 6 6 6 6 6 6]
 [4 4 5 6 6 6 6 6 6]] 



---

<a id="section104"></a> 
<h2><font color="#004D7F" size=4> Unión de arrays </font></h2>
<br>
    
Es posible concatenar o apilar arrays. La función `concatenate()` permite unir dos o más arrays con las mismas dimensiones en la dimensión (existente) especificada. 

<div class="alert alert-block alert-warning">
    
<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
Es muy importante que los tamaños de los arrays permitan llevar a cabo esta operación. 
</div>

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))         # Une los arrays verticalmente (filas)
print()
print(np.concatenate((a, b.T), axis=1))       # Une los arrays horizontalmente (columnas)

[[1 2]
 [3 4]
 [5 6]]

[[1 2 5]
 [3 4 6]]


Las funciones `vstack()` y `hstack()` permiten apilar arrays vertical y horizontalmente. Son equivalentes,  a utilizar  `concatenate()` especificando, respectivamente, los ejes 0 y 1. El siguiente código es equivalente al anterior.

In [11]:
print(np.vstack((a, b)))         # Une los arrays verticalmente (filas)
print()
print(np.hstack((a, b.T)))       # Une los arrays horizontalmente (columnas)

[[1 2]
 [3 4]
 [5 6]]

[[1 2 5]
 [3 4 6]]


La función `stack()` permite unir los arrays a lo largo de una nueva dimensión, que es pasada como parámetro.

In [12]:
arrays = [np.ones((2, 4))*i for i in range(3)]       # Crea 3 arrays de dimensión 2x4
print(arrays[0])
print("------") 
s1 = np.stack(arrays, axis=0)                        # Los apila en un array de dimensión (3,2,4)
print(s1)   
print("------")

s2 = np.stack(arrays, axis=1)                        # Los apila en un array de dimensión (2,3,4)
print(s2)
print("------")

s3 = np.stack(arrays, axis=2)                        # Los apila en un array de dimensión (2,4,3)
print(s3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]]]
------
[[[0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [2. 2. 2. 2.]]

 [[0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [2. 2. 2. 2.]]]
------
[[[0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]]

 [[0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]]]


---

<h3><font color="#004D7F" size=4> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#113D68"></i> Ejercicio</font></h3>

Crear una matriz aleatoria de tamaño 5x5. Añadir una columna a la izquierda en la que todos los valores sean uno.

In [ ]:
# Completar

<div style="text-align: left"><font size=4> <i class="fa fa-check-square-o" aria-hidden="true" style="color:#113D68"></i>
 </font></div>

---

<a id="section105"></a> 
<h2><font color="#004D7F" size=4> Replicación de arrays </font></h2>

Mediante la función `tile()` se puede replicar un array.

In [13]:
a = np.array([0, 1, 2])
m1 = np.tile(a, 2)                  # Concatena a dos veces.          
print(m1)
print()

m2 = np.tile(a, (2, 2))             # Concatena a 2 veces en cada dimensión
print(m2)
print()


a2 = np.array([[1, 2], [3, 4]])     # A partir de un array de dos por dos, crea uno de 4 x 4
m3 = np.tile(a2, (2,2))
print(m3)

[0 1 2 0 1 2]

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]

[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


---

<a id="section106"></a> 
<h2><font color="#004D7F" size=4> División de arrays </font></h2>

Se lleva a cabo con el metodo `split()`, al que se le pasa como parámetro la matriz, los puntos de corte y la dimensión. El método `hsplit()` es similar, pero usa la dimensión 1, es decir, separa por columnas (horizontalmente). El método `vsplit()` usa la dimensión 0, es decir, separa por filas.

In [ ]:
m = np.arange(20).reshape(4,5) 
print(m) 
print()

#splits = np.split(m,[2,3],axis=1)          # Los dos son equivalentes
splits = np.hsplit(m,[2,3])
print(splits)
print(splits[0],'\n')
print(splits[1],'\n')
print(splits[2],'\n')

---

<h3><font color="#004D7F" size=4> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#113D68"></i> Ejercicio</font></h3>


Crear un array de tamaño 100x5 con números aleatorios. Guardar las 60 primeras filas en una variable llamada `X`, las siguientes 20 en otra, llamada `V`, y las últimas 20 en otra llamada `T`.

In [ ]:
# Completar

<div style="text-align: left"><font size=4> <i class="fa fa-check-square-o" aria-hidden="true" style="color:#113D68"></i>
 </font></div>

---
<a id="section107"></a> 
<h2><font color="#004D7F" size=4> Adición y borrado de elementos </font></h2>

La función `append()` permite añadir elementos al final de un array. Esta operación genera un nuevo array. Además, las dimensiones del array y del array con los elementos deben coincidir. 

In [ ]:
m = np.array([[1,2,3],[4,5,6]]) 
print(m)
print()

m2 = np.append(m, [7,8,9])             # Si no se especifica dimensión genera un vector y añade al final
print(m2)
print()

m3 = np.append(m, [[7,8,9]], axis = 0) # Aquí añade un elemento que es, a su vez, una lista. Lo añade como fila.
print(m3)
print()

m4 =  np.append(m, [[5,5,5],[7,8,9]],axis = 1) # Añade dos elementos en la dimensión 1, es decir, como dos columnas.
print(m4)

La función `insert()` permite insertar elementos a partir de un índice, y en la dimensión especificada.

In [ ]:
m = np.array([[1,2],[3,4],[5,6]]) 
print(m)
print()

m1 = np.insert(m,3,[10,20])        # Como no se pasa dimensión, convierte a vector e inserta en la posición 3 los valores.
print(m1)
print()

m2=np.insert(m,1,[10, 10],axis = 0)    # En este caso se añade una fila.
print(m2)
print()

m3=np.insert(m,1,[10, 10, 10] ,axis = 1)   # Este ejemplo es similar al anterior, pero se añade una columna (la uno)
print(m3)
print()

La función `delete()` permite eliminar elementos de un array. Funciona como `insert()`. Es decir, elimina los elementos en la dimensión especificada y, si no se especifica ninguna, convierte el array a un vector unidimensional primero.

In [ ]:
m = np.arange(12).reshape(3,4) 
print(m)
print()

m1 = np.delete(m,[5,7])                 # Borra los elementos 5 y 7
print(m1)
print()

m2 = np.delete(m,1,axis = 1)            # Borra la columna 1
print(m2)


<div style="text-align: right"> <font size=5>
    <a href="#indice"><i class="fa fa-arrow-circle-up" aria-hidden="true" style="color:#004D7F"></i></a>
</font></div>

---

<a id="section11"></a> 
<h2><font color="#004D7F" size=5> 11. Arrays con tipos de datos heterogéneos y estructurados </font></h2>
<br>

Los arrays pueden contener elementos de distinto tipo.

In [ ]:
m = np.array([[('Diana',21), ('Alicia',25)],[('Carmen', 17), ('Benito',27)]]) 
print(m[0][0])
print(list(map(type, m[0][0])))
print(m.shape)

Numpy permite, además, crear tipos de datos estructurados.

In [ ]:
persona = np.dtype([('nombre', 'S10'),('edad', int)]) 
m = np.array([[('Diana',21), ('Alicia',25)],[('Carmen', 17), ('Benito',27)]], dtype = persona) 
print("Cambia la forma: ",m.shape)

En el caso de que el array sea de valores con un tipo estructurado, se puede acceder de manera independiente a cada uno de los campos.

In [ ]:
m['edad']

También es posible ordenar el array en función de un campo.

In [ ]:
print (np.sort(m, order = 'nombre'))

<div style="text-align: right"> <font size=5>
    <a href="#indice"><i class="fa fa-arrow-circle-up" aria-hidden="true" style="color:#004D7F"></i></a>
</font></div>

---

<a id="section12"></a> 
<h2><font color="#004D7F" size=5> 12. Almacenamiento de datos </font></h2>
<br>

Además de las estructuras `pickle` utilizadas en Python para serialización, es posible cargar y salvar arrays Numpy con las funciones `save()`\ `savetxt()` y `load()` \ `loadtxt()`. Las funciones `load()` y `save()` almacenan los datos en un archivo binario con extensión `npy`. Las funciones `loadtxt()` y `savetxt()` lo hacen en un archivo de texto.

In [ ]:
m = np.random.random((4,5))
print(m)

np.save('matriz',m)                 # Salva la matriz en formato binario
np.savetxt('matriz.txt', m)         # Salva la matriz en el archivo de texto matriz.txt

<font size=4> <i class="fa fa-book" aria-hidden="true" style="color:#004D7F"></i> </font> Desde jupyter se pueden invocar órdenes del shell del sistema anteponiéndolas de `!`. Por ejemplo, para ver los archivos creados.

In [ ]:
! ls

In [ ]:
m2 = np.loadtxt('matriz.txt')       # Carga el archivo de texto
print(m1)

<div style="text-align: right"> <font size=5>
    <a href="#indice"><i class="fa fa-arrow-circle-up" aria-hidden="true" style="color:#004D7F"></i></a>
</font></div>

---

<a id="section13"></a> 
<h2><font color="#004D7F" size=5> 13. <i>Broadcasting</i> </font></h2>
<br>

El _Broadcasting_ es un mecanismo que permite llevar a cabo operaciones aritméticas con arrays de dimensiones diferentes.  Se suele aplicar sobre un array más pequeño y otro más grande. Generalmente, se utiliza el array más pequeño múltiples veces para hacer una operación en el más grande. Para aplicar _broadcasting_ sobre dos arrays, se deben cumplir unas condiciones. Información detallada al respecto puede consultarse [aquí](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).

# <img src="numpy_broadcasting.png" alt="Broadcasting" width=600 hight=400 align="center">

En el siguiente ejemplo se define una matriz de cuatro filas y tres columnas, y se suma un vector de tres elementos a cada una de las filas.

In [2]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = m + v                
print(m)
print()
print(v)
print()
print(y)  +         # Por ejemplo, la primera fila es [1+1, 2+0, 3+1]; la segunda [4+1, 5+0, 6+1]4

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Existe una función, denominada `broadcast()`, cuyo objetivo es imitar el funcionamiento del _broadcasting_. El siguente código muestra un ejemplo de uso frecuente de _broadcasting_.

In [3]:
x = np.array([[1,2,3],[4,5,6]])
print(x,"\n")
y = np.array([1,10,100])
print(y,"\n")
b = np.broadcast(x,y)            # Devuelve un iterador. Cada elemento es una tupla con un elemento del primer vector
for i in b:                      # y otra del segundo.
    print(i,end=" ")
print()

b = np.broadcast(x,y)  
m = np.empty(b.shape)            # Crea una matriz vacía con las dimensiones del broadcast
m.flat =[u*v for (u,v) in b]     # Para copiar los elementos de uno en uno utiliza flat. Usa como ejemplo
                                 # el producto de fila y columna
print(m)                         # Ahora imprime la matriz

[[1 2 3]
 [4 5 6]] 

[  1  10 100] 

(1, 1) (2, 10) (3, 100) (4, 1) (5, 10) (6, 100) 
[[  1.  20. 300.]
 [  4.  50. 600.]]


<div style="text-align: right"> <font size=5>
    <a href="#indice"><i class="fa fa-arrow-circle-up" aria-hidden="true" style="color:#004D7F"></i></a>
</font></div>

---

<div style="text-align: right"> <font size=6><i class="fa fa-coffee" aria-hidden="true" style="color:#004D7F"></i> </font></div>